name: hisabi
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.1.0
  home_widget: ^0.7.0
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  share_plus: ^10.0.2
  path_provider: ^2.1.5
  cross_file: ^0.3.4
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - lib/assets/logo.svg
